version: '3'
services:
  nodeapp:
    container_name: nodeappcontainer
    build: ./
    # image:  ${IMAGE}:${IMAGE_TAG}
    volumes:
      - ./nodeapp:/code
    environment:
      - DB_HOST=db
      - DB_USER=besbes
      - DB_PASSWORD=letmein
      - DB_NAME=auctiondb
      - DB_PORT=3306
      - SERVER_PORT=3001
      - ACCESS_TOKEN_SECRET="f72636373028229ffdefd0840161533f1f67ab1d9c60c736057bba4c7b72cbc1ffa69f84ff71385b583fb8443504d4a3fd796556a8e5b63e930886b1e4122467"
      - Refresh_TOKEN_SECRET="47a41301a5a8d7c7288bafb123f71c18f3af95f24a5ee0c22b82729adb32d6e55cdddfc9440e3debfe4ea747dcaf16d23429dbff32b3e6286ee77e3820567c80"
    ports:
      - 3001:3001
    expose:
      - 3001
networks:
  default:
    name: deployapp_default
