version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: auctiondb
      MYSQL_USER: mahdi
      MYSQL_PASSWORD: letmein
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/0_init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    links:
      - db
    environment:
      PMA_HOST: mysqlcontainer
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
networks:
  default:
    name: auctiondb_default
volumes:
  dbdata:
  