apiVersion: apps/v1
kind: Deployment
##metadata contains the labels spec contains selectors
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
##specification for deployment(desired not the status status inside etcd)
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  ##spec for pod( the spec that i want (desired))
  template:
    metadata:
      labels:
        app : phpmyadmin
    spec:
      containers:
      - name : phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:  
        - containerPort: 80
        env:
        - name : PMA_HOST
          value: "mysql-primary"
        - name : PMA_ARBITRARY 
          value : "1"
        - name : PMA_PORT
          value :  "3306"
---
apiVersion: v1
kind: Service
metadata:
  name:  phpmyadmin
  labels:
    app: phpmyadmin
##spec for Service
spec: 
  selector:
    app: phpmyadmin
  ##accepts external requests by assinging the service an external ip adress
  ports:
    - protocol: TCP
      port : 80
      #to wich pod it should forward the 
      targetPort: 80

